### ISSUE TITLE
 hi man, Would it be possible to make it work with both mouse buttons?

### ISSUE THREAD

**Issue by Allmight00001** [IceyFL/The-Finals-AI-Cheat#1]
hi man, Would it be possible to make it work with both mouse buttons?

**Comment by IceyFL** [comment]
wdym

**Comment by Allmight00001** [comment]
> wdym

If there is a way to make the script activate the aimbot on both mouse buttons at the same time, just press the left or right button

**Comment by IceyFL** [comment]
could you not just use constant aimbot?

**Comment by Allmight00001** [comment]
> você não poderia simplesmente usar o aimbot constante?

In battleroyale style games it can be a problem, due to false detections or random objects

**Comment by IceyFL** [comment]
ill think about it

**Comment by IceyFL** [comment]
ima bouta release it

**Comment by IceyFL** [comment]
oh nvm i added it to my undetected aimmy one
i didnt relise the issue was on the finals
check this out
https://github.com/IceyFL/Undetected-Aimmy

**Comment by Allmight00001** [comment]
> ah, nvm, adicionei ao meu objetivo não detectado, não sabia que o problema estava nas finais, confira https://github.com/IceyFL/Undetected-Aimmy

nice thx man good job
