### ISSUE TITLE
Any chance we could get an update?

### ISSUE THREAD

**Issue by GAMERGOD2636** [IceyFL/The-Finals-AI-Cheat#2]
As I'm sure you already know, THE FINALS recently had an update. That said, I was wondering if you could check the detectability and update the anti recoil script to include the new weapons (of course, in only referring to the automatic ones). Time isn't really a bother at all. Please ping me when you respond. I might not see your response otherwise.

**Comment by IceyFL** [comment]
@GAMERGOD2636 i dont play much anymorfe but maybe at some point

**Comment by GAMERGOD2636** [comment]
> @GAMERGOD2636 i dont play much anymorfe but maybe at some point

Ok, thank you! Also, do you use Lew29's AHK (anti-recoil) script for the menu? Only asking because he's willing to update it as long as it's not detected.

**Comment by IceyFL** [comment]
i dont know i just got the values of of unknown cheats

**Comment by GAMERGOD2636** [comment]
Ok. Well, I'm looking forward to the potential release of an update!
